name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Testing tarring
      run: go test github.com/s-vvardenfell/tegrum/archiver/tarring

    - name: Testing zipping
      run: go test github.com/s-vvardenfell/tegrum/archiver/zipping
            
    - name: Running
      run: go run main.go
